import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import Header from '@/components/Header';
import Footer from '@/components/Footer';
// import { CartContextProvider } from '../lib/CartContext';
// import { SessionProvider } from 'next-auth/react';
import { Toaster } from 'react-hot-toast';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Header />
				<Toaster position="top-center" />
				<main
					className={`${inter.className} h-full max-w-screen-2xl mx-auto bg-background sm:px-6`}
				>
					{children}
				</main>
				<Footer />
			</body>
		</html>
	);
}
